
const actionTypes = {
    UPDATE_TOKENS_SUCCESS: 'UPDATE_TOKENS_SUCCESS',
    UPDATE_TOKENS_FAILD: 'UPDATE_TOKENS_FAILD',
    GET_LOGIN_START: 'GET_LOGIN_START',
    GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
    GET_LOGIN_FAILD: 'GET_LOGIN_FAILD',
    USER_LOGOUT: 'USER_LOGOUT'
}

export default actionTypes;