
const actionTypes = {
    UPDATE_TOKENS_SUCCESS: 'UPDATE_TOKENS_SUCCESS',
    UPDATE_TOKENS_FAILD: 'UPDATE_TOKENS_FAILD',
    GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
    GET_LOGIN_FAILD: 'GET_LOGIN_FAILD',
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    DELETE_CURRENT_USER: 'DELETE_CURRENT_USER'
}

export default actionTypes;